### ISSUE TITLE
Check system.disk - error on RouterOS 6.49.10

### ISSUE THREAD

**Issue by alexoalexo** [DinoTools/monitoring-check_routeros#98]
Hello,
check system.disk works fine on ver7 but I get the following error on v.6.49.10

```
DISK UNKNOWN: KeyError: 'write-sect-since-reboot'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nagiosplugin/runtime.py", line 44, in wrapper
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/nagios/custom-plugins/routeros_check/check/system_disk.py", line 155, in system_disk
    check.main(verbose=ctx.obj["verbose"])
  File "/usr/lib/python3/dist-packages/nagiosplugin/check.py", line 121, in main
    runtime.execute(self, verbose, timeout)
  File "/usr/lib/python3/dist-packages/nagiosplugin/runtime.py", line 131, in execute
    self.run(check)
  File "/usr/lib/python3/dist-packages/nagiosplugin/runtime.py", line 118, in run
    check()
  File "/usr/lib/python3/dist-packages/nagiosplugin/check.py", line 106, in __call__
    self._evaluate_resource(resource)
  File "/usr/lib/python3/dist-packages/nagiosplugin/check.py", line 73, in _evaluate_resource
    metrics = resource.probe()
              ^^^^^^^^^^^^^^^^
  File "/usr/lib/nagios/custom-plugins/routeros_check/check/system_disk.py", line 45, in probe
    results = self.get_routeros_metric_item(api_result_items[0])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/nagios/custom-plugins/routeros_check/resource.py", line 329, in get_routeros_metric_item
    value = api_result[metric_value_name]
            ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
KeyError: 'write-sect-since-reboot'

```

**Comment by phibos** [comment]
Closing this issue due to missing information. Please provide the requested details and reopen or create a new issue if the problem continues.
